.PHONY: clean All

All:
	@echo "----------Building project:[ stock - Debug ]----------"
	@cd "stock" && "$(MAKE)" -f  "stock.mk"
clean:
	@echo "----------Cleaning project:[ stock - Debug ]----------"
	@cd "stock" && "$(MAKE)" -f  "stock.mk" clean
